
"src/net/dos4gw/ipx.cc",
  "src/specache.cc",
  "../zebra_imlib/sprite.cc",
  "src/netcfg.cc",
  "src/text_gui.cc",
  "src/innet.cc",                  
  "src/net/unix/gserver.cc.cc", 
  "src/net/unix/gclient.cc",          "src/net/unix/fileman.cc",           "src/net/sock",
  "src/chat.cc",     "src/endgame.cc",   "src/setup.cc",      "src/version.cc",  "src/loadgame.cc",  "src/profile",
  "src/cop.cc",       "src/statbar.cc",  "src/compiled.cc",   "src/ant.cc",      "src/sensor.cc",
  "src/lisp_opt.cc",  "src/demo.cc",     "src/lcache.cc",     "src/lisp_gc",
  "src/nfclient.cc",  "src/username.cc", "src/clisp.cc",      "src/gui.cc",
  "src/transp.cc",    "src/collide.cc",  "src/trig.cc",       "src/property.cc",
  "src/lisp.cc",      "src/cache.cc",    "src/particle.cc",   "src/objects",
  "src/extend.cc",    "src/console.cc",  "src/ability.cc",
  "src/items.cc",     "src/dev.cc",      "src/chars.cc",       
  "src/level.cc",   "src/smallfnt.cc","src/automap.cc",
  "src/help.cc",      "src/intsect.cc",  "src/loader2.cc",      "src/seq.cc",     
  "src/points.cc",    "src/fnt6x13.cc",  "src/morpher.cc",     
  "src/menu.cc",    "src/director.cc","src/view.cc",
  "src/config.cc",    "src/game.cc",     "src/light.cc",       "src/devsel.cc",
  "src/crc.cc",       "src/gamma.cc",    "src/language.cc",
